FROM node:16.18-alpine as build
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm ci
WORKDIR /opt/app
COPY ./ .
RUN npm run build


FROM node:16.18-alpine
WORKDIR /opt/app
COPY --from=build /opt/node_modules ./node_modules
ENV PATH /opt/node_modules/.bin:$PATH
COPY --from=build /opt/app ./
EXPOSE 3000
CMD HOST=0.0.0.0 PORT=3000 node ./dist/server/entry.mjs