version: '3.8'
services:
  pgdb:
    image: postgres:14.6
    restart: always
    container_name: postgresDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123!
    ports:
      - '5432:5432'
    volumes: 
      - pgdb:/var/lib/postgresql/data
      #- ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      pgBridge:
        ipv4_address: 172.1.1.23
volumes:
  pgdb:
    driver: local

networks:
  pgBridge:
    external: true
    ipam:
      config:
        - subnet: 172.1.1.0/24